import { Header } from "@/components/layouts/header";
import { MainContainer } from "@/components/layouts/main-container";
import { Sidebar } from "@/components/layouts/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SIDEBAR_COOKIE_NAME } from "@/constants/sidebar";
import { QueryProvider } from "@/providers/query-provider";
import { SidebarProvider } from "@/providers/sidebar-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import localFont from "next/font/local";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";

const pretendard = localFont({
  src: "../styles/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const initialIsOpen = cookieStore.get(SIDEBAR_COOKIE_NAME)?.value !== "false";

  return (
    <html
      lang="ko"
      className={pretendard.className + " " + pretendard.variable + " h-full antialiased"}
      suppressHydrationWarning
    >
      <body className="min-h-dvh">
        <ThemeProvider>
          <TooltipProvider>
            <SidebarProvider initialIsOpen={initialIsOpen}>
              <div className="flex h-dvh flex-col overflow-hidden bg-background">
                <Header />
                <div className="flex min-h-0 flex-1">
                  <Sidebar />
                  <div className="@container flex min-h-0 min-w-0 flex-1 flex-col overflow-y-auto bg-background">
                    <NuqsAdapter>
                      <QueryProvider>
                        <MainContainer>{children}</MainContainer>
                      </QueryProvider>
                    </NuqsAdapter>
                  </div>
                </div>
              </div>
            </SidebarProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
